version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db
    networks:
      - taskmanagement_network

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagement
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - taskmanagement_network

volumes:
  postgres_data:
    
networks:
  taskmanagement_network:
    driver: bridge